pngquant ../Configs/Default/Android/*.png --ext .png --force --skip-if-larger
pngquant ../Configs/Default/Android/icons/*.png --ext .png --force --skip-if-larger
pngquant ../Configs/Default/HTML5/*.png --ext .png --force --skip-if-larger
pngquant ../Configs/Default/iOS/*.png --ext .png --force --skip-if-larger
pngquant ../Configs/Default/iOS/icons/*.png --ext .png --force --skip-if-larger
pngquant ../Configs/Default/Linux/*.png --ext .png --force --skip-if-larger
pngquant ../Configs/Default/Mac/*.png --ext .png --force --skip-if-larger
pngquant ../Configs/Default/Tizen/*.png --ext .png --force --skip-if-larger
pngquant ../Configs/Default/windows/*.png --ext .png --force --skip-if-larger
pngquant ../Configs/Default/Windows8/*.png --ext .png --force --skip-if-larger
pngquant ../Configs/Default/Windows8/logos/*.png --ext .png --force --skip-if-larger
pngquant ../Configs/Default/WinPhone/*.png --ext .png --force --skip-if-larger
